[tool.poetry]
name = "hanzo-kms"
version = "1.0.0"
description = "Official Hanzo KMS Python SDK"
authors = ["Hanzo AI, Inc. <support@hanzo.ai>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/hanzokms/python-sdk"
keywords = ["Hanzo", "KMS", "Secrets Management", "SDK"]
include = ["hanzo_kms/py.typed"]

[tool.poetry.dependencies]
python = ">=3.14"

python-dateutil = ">=2.8.2"
aenum = ">=3.1.11"

[tool.poetry.dev-dependencies]
pytest = ">=7.2.1"
tox = ">=3.9.0"
flake8 = ">=4.0.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
